sudo: require
dist: trusty
language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra


script:
  - bash tests/test.sh classic
  - bash tests/test.sh modern
  - bash tests/test.sh two_column
  - bash tests/test.sh infographics
